"""``loom autopsy``: the one report you hand to a manager or a security review.

Loom already produces the pieces -- timeline, impact map, data flow, root
cause, score, fix. ``loom autopsy`` assembles them into a single self-contained
HTML page: what happened, what it touched, what leaked, why, the behavior
score, and the recommended fix + policy. One artifact, not eight.

    loom autopsy failed.loom.json           # -> failed.autopsy.html
"""

from __future__ import annotations

import html as _html


def autopsy_html(data: dict, path: str = "trace.loom.json") -> str:
    """Assemble the full autopsy report for a trace dict."""
    from .diagnose import diagnose
    from .diff import score_badge_svg, score_breakdown
    from .report_panels import _data_flow, _impact_map
    from .incident import build_report
    from .packs import install_builtin
    from .taint import dlp_report

    install_builtin()
    d = diagnose(data, path)
    bd = score_breakdown(data)
    dlp = dlp_report(data)
    prompt = (data.get("episodes") or [data.get("prompt", "")])[0]

    dims = "".join(
        f'<tr><td>{k.replace("_", " ")}</td><td class="num">{v["score"]}</td>'
        f'<td>{_html.escape(v["why"])}</td></tr>'
        for k, v in bd["dimensions"].items())

    dlp_html = ""
    if dlp["violations"]:
        rows = "".join(
            f'<li><b>{_html.escape(p["sensitivity"])} · {p["severity"]}</b> '
            f'({_html.escape(p["kind"])} {_html.escape(p["value_preview"])}): '
            f'[{p["source"]["step"]}] {_html.escape(p["source"]["tool"])} → '
            f'[{p["sink"]["step"]}] {_html.escape(p["sink"]["tool"])}</li>'
            for p in dlp["violations"])
        sugg = "".join(f"<li>{_html.escape(i['suggestion'])}</li>"
                       for i in dlp["by_class"].values())
        dlp_html = (f'<h2>Data leaks (worst: {dlp["worst_severity"]})</h2><ul>{rows}</ul>'
                    f'<p><b>Suggested policy:</b></p><ul>{sugg}</ul>')

    # Reuse the incident report's blast-radius / prevention narrative (as text).
    incident = _html.escape(build_report(data, path))

    verify = "".join(f"<li><code>{_html.escape(c)}</code></li>" for c in d["verify"])
    css = """:root{--surface:#fff;--page:#f9f9f7;--ink:#0b0b0b;--ink-2:#52514e;
    --muted:#898781;--grid:#e1e0d9;--ring:rgba(11,11,11,.10);--meta:#4a3aa7;--warn:#fab219;--tool:#1baf7a}
    @media(prefers-color-scheme:dark){:root{--surface:#1a1a19;--page:#0d0d0d;--ink:#fff;
    --ink-2:#c3c2b7;--grid:#2c2c2a;--ring:rgba(255,255,255,.10)}}
    body{font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
    max-width:900px;margin:0 auto;padding:34px;color:var(--ink);background:var(--page)}
    @media(prefers-color-scheme:dark){
    .panel,table{background:#1a1a19!important;border-color:#2c2c2a!important}}
    h1{font-size:26px;margin-bottom:2px}.sub{color:#898781;margin-bottom:18px}
    h2{font-size:15px;color:#52514e;text-transform:uppercase;letter-spacing:.05em;
    margin:26px 0 8px;border-bottom:1px solid #e1e0d9;padding-bottom:4px}
    .panel{background:#fff;border:1px solid #e1e0d9;border-radius:12px;padding:14px 18px;margin:8px 0}
    .verdict{font-size:18px;font-weight:650}
    table{width:100%;border-collapse:collapse;background:#fff;border:1px solid #e1e0d9;border-radius:10px;overflow:hidden}
    td{padding:6px 12px;border-bottom:1px solid #eee}td.num{text-align:right;font-variant-numeric:tabular-nums;font-weight:600}
    pre{white-space:pre-wrap;background:#f2f2ef;border:1px solid #e1e0d9;border-radius:10px;padding:12px;font-size:12.5px;overflow-x:auto}
    @media(prefers-color-scheme:dark){pre{background:#111}}
    code{font-size:13px}svg{max-width:100%}
    .badge{margin:6px 0}"""
    return f"""<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Autopsy — {_html.escape(prompt[:60])}</title><style>{css}</style></head><body>
<h1>🧾 Agent run autopsy</h1>
<p class="sub">“{_html.escape(prompt[:140])}”</p>

<div class="panel verdict">Diagnosis: {_html.escape(d['failure'])}
  &nbsp;·&nbsp; severity {_html.escape(d['severity'])}
  &nbsp;·&nbsp; fix category {_html.escape(d['fix_category'])}</div>

<h2>Behavior score</h2>
<div class="badge">{score_badge_svg(bd['overall'])}</div>
<table><tr><td><b>overall</b></td><td class="num">{bd['overall']}</td><td></td></tr>{dims}</table>

<h2>What it touched</h2>
{_impact_map(data) or "<p>nothing changed in the world</p>"}

{_data_flow(data)}
{dlp_html}

<h2>Root cause</h2>
<div class="panel">{_html.escape(d['diagnosis'])}<br><br>
<b>Fix ({_html.escape(d['fix_category'])}):</b> {_html.escape(d['suggestion'])}</div>
<p><b>Verify the fix:</b></p><ul>{verify}</ul>

<h2>Incident report</h2>
<pre>{incident}</pre>

<footer style="color:#898781;font-size:12px;margin-top:28px">
generated by loom autopsy — replay it: <code>loom studio {_html.escape(path)}</code>,
watch it: <code>loom movie {_html.escape(path)}</code></footer>
</body></html>"""
