"""``loom autopilot``: turn an incident into a ready-to-merge fix bundle.

When a run fails, leaks, or trips a policy, the response is always the same
manual sequence: figure out the root cause, write it up, capture a regression,
propose a policy change, open a PR. ``autopilot`` does all of it from one trace:

    loom autopilot incident.loom.json -o fix/         # the whole bundle
    loom autopilot incident.loom.json -o fix/ --open-pr

It writes a self-contained autopsy + a 30-second incident movie, a root-cause
diagnosis, a synthesized policy patch that would have stopped it, a regression
fixture + test that fails on the bad behavior, and a PR body tying them
together. "Agent had an incident → Loom opened the fix PR."
"""

from __future__ import annotations

import json
import os
from typing import Any


def run_autopilot(trace_path: str, outdir: str) -> dict:
    """Generate the full incident-response bundle in ``outdir``. Returns a manifest."""
    from .autopsy import autopsy_html
    from .diagnose import describe_diagnosis, diagnose
    from .incident import build_report
    from .movie import movie_html
    from .scan import scan
    from .synth import to_yaml

    os.makedirs(outdir, exist_ok=True)
    with open(trace_path) as f:
        data = json.load(f)

    diag = diagnose(data, path=trace_path)
    scan_rep = scan(data)
    artifacts: dict[str, str] = {}

    def _write(name: str, content: str) -> None:
        p = os.path.join(outdir, name)
        with open(p, "w") as fh:
            fh.write(content)
        artifacts[name] = p

    _write("autopsy.html", autopsy_html(data, path=trace_path))
    _write("movie.html", movie_html(data))
    _write("incident.md", build_report(data, trace_path))
    _write("diagnosis.md", "# Root cause\n\n" + describe_diagnosis(diag, plan=True))

    # a targeted policy patch: deny/confirm the dangerous tools this run used
    deny, confirm = [], []
    for t in scan_rep["tools"]:
        caps = set(t["capabilities"])
        if caps & {"destructive", "money_movement"}:
            deny.append(f"{t['name']}*")
        elif caps & {"database_write", "browser_submit", "exec", "network", "user_communication"}:
            confirm.append(f"{t['name']}*")
    patch = {"default": "allow", "allow": [], "confirm": sorted(set(confirm)),
             "deny": sorted(set(deny)),
             "_synthesized": {"goal": "incident-patch", "from_runs": 1,
                              "tools_seen": len(scan_rep["tools"])}}
    _write("policy-patch.yml", to_yaml(patch))

    # a regression fixture + test (scrubbed fixture, policy gate, pytest)
    reg_ok = False
    try:
        from .regression import build_regression
        reg = build_regression(trace_path, os.path.join(outdir, "regression"))
        artifacts["regression"] = reg.get("dir", os.path.join(outdir, "regression"))
        reg_ok = True
    except Exception:  # noqa: BLE001 -- regression is best-effort
        reg_ok = False

    category = diag.get("category", "unknown")
    cause = diag.get("suggestion", "") or diag.get("classification", "")
    pr_body = f"""# 🤖 Loom autopilot: fix for `{os.path.basename(trace_path)}`

**Category:** {category}
**Root cause:** {cause}
**Grade:** {scan_rep['grade']} · dangerous-but-ungated tools: {', '.join(
        f['tool'] for f in scan_rep['findings'] if f['severity'] == 'high' and f.get('tool')) or 'none'}

## What's in this bundle
- `autopsy.html` — one-page incident autopsy
- `movie.html` — 30-second replay of what happened
- `diagnosis.md` — root cause + verify plan
- `policy-patch.yml` — a firewall change that would have stopped it
  ({len(deny)} deny, {len(confirm)} confirm)
- `regression/` — a fixture + test that fails on the bad behavior{'' if reg_ok else ' (skipped)'}

## Verify
```bash
loom policy rollout policy-patch.yml --traces runs/   # gate before enforcing
```

🤖 Generated by `loom autopilot`.
"""
    _write("PR-BODY.md", pr_body)
    return {"outdir": outdir, "artifacts": artifacts, "category": category,
            "grade": scan_rep["grade"], "deny": deny, "confirm": confirm}


def open_pr(outdir: str, slug: str = "loom-autopilot-fix") -> "tuple[bool, str]":
    """Commit the bundle on a branch and open a GitHub PR (needs git + gh)."""
    import subprocess

    def _run(args):
        return subprocess.run(args, cwd=outdir, capture_output=True, text=True)

    branch = slug
    try:
        _run(["git", "checkout", "-b", branch])
        _run(["git", "add", "-A"])
        _run(["git", "commit", "-m", f"Loom autopilot: incident fix ({slug})"])
        _run(["git", "push", "-u", "origin", branch])
        body = os.path.join(outdir, "PR-BODY.md")
        r = _run(["gh", "pr", "create", "--title", "Loom autopilot: incident fix",
                  "--body-file", body])
        return (r.returncode == 0, (r.stdout or r.stderr).strip())
    except (OSError, subprocess.SubprocessError) as e:
        return (False, str(e))


def describe_autopilot(manifest: dict) -> str:
    lines = [f"🤖 autopilot bundle → {manifest['outdir']}  (category: {manifest['category']}, "
             f"grade {manifest['grade']})"]
    for name in manifest["artifacts"]:
        lines.append(f"  · {name}")
    if manifest["deny"] or manifest["confirm"]:
        lines.append(f"  policy patch: {len(manifest['deny'])} deny, "
                     f"{len(manifest['confirm'])} confirm")
    return "\n".join(lines)
