"""``loom behavior``: turn an agent run into behavior unit tests.

Replay proves a run is reproducible; it doesn't say what *correct behavior* is.
``behavior`` reads a good run and extracts a **behavior contract** -- the tools
it used, the order it used them in, safety invariants it respected (no network
after reading PII), its cost ceiling, and whether it stayed clean of risky /
blocked calls -- then emits a pytest that checks any trace against that contract:

    loom behavior good.loom.json --pytest test_agent_behavior.py

Now "the agent must look up the order before issuing a refund" and "must not
reach the network after touching PII" are unit tests in CI, not tribal knowledge.
"""

from __future__ import annotations

import json
from typing import Any


def behavior_spec(source: Any) -> dict:
    """Extract a behavior contract from a (good) run."""
    from .action import actions

    acts = [a for a in actions(source) if a.type == "call" and a.tool]
    tools = [a.tool for a in acts]
    seen: list[str] = []
    for t in tools:
        if t not in seen:
            seen.append(t)
    # ordering pairs: X first appears before Y (a required-before contract)
    order: list[list[str]] = []
    for i, a in enumerate(seen):
        for b in seen[i + 1:]:
            order.append([a, b])

    # cost ceiling from the run's own spend (+25% headroom)
    from .cost import analyze_cost
    total = analyze_cost(source if isinstance(source, dict) else source.to_dict())["total_tokens"]
    max_tokens = int(total * 1.25) + 500

    # safety invariant: did any egress happen AFTER a PII/secret access?
    exfil_shape = False
    touched_sensitive = False
    for a in acts:
        caps = set(a.capabilities)
        if caps & {"pii_access", "secret"}:
            touched_sensitive = True
        if touched_sensitive and caps & {"network", "user_communication"}:
            exfil_shape = True

    risky = sorted({a.tool for a in acts if a.risky})
    return {
        "tools_used": seen,
        "required_order": order[:12],
        "max_tokens": max_tokens,
        "no_egress_after_sensitive": not exfil_shape,
        "risky_tools": risky,
        "no_risky_calls": not risky,
    }


def to_pytest(spec: dict, trace_path: str = "run.loom.json") -> str:
    """A self-contained pytest that checks a trace against the behavior contract."""
    return f'''"""Behavior contract generated by `loom behavior`. Point TRACE at the run to check."""
import json
from loom.action import actions

TRACE = {trace_path!r}
SPEC = {spec!r}


def _calls(data):
    return [a for a in actions(data) if a.type == "call" and a.tool]


def _data():
    with open(TRACE) as f:
        return json.load(f)


def test_uses_expected_tools():
    used = {{a.tool for a in _calls(_data())}}
    missing = set(SPEC["tools_used"]) - used
    assert not missing, f"expected tools not used: {{missing}}"


def test_required_tool_order():
    seq = [a.tool for a in _calls(_data())]
    for before, after in SPEC["required_order"]:
        if before in seq and after in seq:
            assert seq.index(before) <= seq.index(after), \\
                f"{{before}} must be called before {{after}}"


def test_cost_under_ceiling():
    from loom.cost import analyze_cost
    assert analyze_cost(_data())["total_tokens"] <= SPEC["max_tokens"]


def test_no_egress_after_sensitive():
    if not SPEC["no_egress_after_sensitive"]:
        return  # the reference run itself had this shape; not an invariant
    touched = False
    for a in _calls(_data()):
        caps = set(a.capabilities)
        if caps & {{"pii_access", "secret"}}:
            touched = True
        assert not (touched and caps & {{"network", "user_communication"}}), \\
            f"egress ({{a.tool}}) after sensitive access -- possible exfiltration"


def test_no_risky_calls():
    if SPEC["no_risky_calls"]:
        risky = [a.tool for a in _calls(_data()) if a.risky]
        assert not risky, f"unexpected risky calls: {{risky}}"
'''


def describe_behavior(spec: dict) -> str:
    lines = ["behavior contract:",
             f"  tools: {', '.join(spec['tools_used']) or '(none)'}",
             f"  ordering constraints: {len(spec['required_order'])}",
             f"  cost ceiling: {spec['max_tokens']:,} tokens",
             f"  no egress after sensitive access: {spec['no_egress_after_sensitive']}",
             f"  no risky calls: {spec['no_risky_calls']}"]
    return "\n".join(lines)
